language: node_js
node_js:
  - '0.12'
before_install:
  - npm install -g bower grunt-cli
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/911ed472ef19bcb27858
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
